unit TestUnit1Antri;
{

  Delphi DUnit Test Case
  ----------------------
  This unit contains a skeleton test case class generated by the Test Case Wizard.
  Modify the generated code to correctly setup and call the methods from the unit 
  being tested.

}

interface

uses
  TestFramework, DUnitX.TestFramework, Unit1Antri;

type
  // Test methods for class TAntriTest

  TestTAntriTest = class(TTestCase)
  strict private
    FAntriTest: TAntriTest;
  public
    procedure SetUp; override;
    procedure TearDown; override;
  end;

implementation

procedure TestTAntriTest.SetUp;
begin
  FAntriTest := TAntriTest.Create;
end;

procedure TestTAntriTest.TearDown;
begin
  FAntriTest.Free;
  FAntriTest := nil;
end;

initialization
  // Register any test cases with the test runner
  RegisterTest(TestTAntriTest.Suite);
end.

